[workspace]
members = [
    "dcspkg",
    "dcspkg-client",
    "dcspkg-server",
    "dcspkg-create",
    "dcspkg-common",
]

[workspace.metadata.release]
consolidate-pushes = true
consolidate-commits = true
