version: "3.9"
services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./packages
        target: /mnt/packages
    environment:
      - PACKAGE_PATH=/mnt/packages/packages
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_DATABASES={packagedb={url=/mnt/packages/packagedb.sqlite}}
