version: "3.9"
services:
  server:
    network_mode: bridge
    build: .
    ports:
      - "8123:8123"
    volumes:
      - type: bind
        source: /home/uwucs/packages
        target: /mnt/packages
        volume:
          nocopy: true
    environment:
      - PACKAGE_PATH=/mnt/packages/packages
      - DB_PATH/mnt/packages/packagedb.sqlite
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8123
