name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Check code builds without warnings
        run: cargo check --verbose --workspace

  lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: build
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v2
      - name: Run clippy
        run: cargo clippy --verbose --workspace
      - name: Check formatting
        run: cargo fmt --check --verbose

  test:
    runs-on: ubuntu-latest
    name: Test
    needs: build
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v2
      - name: Run Cargo tests
        run: cargo test --verbose

  docker_publish:
    runs-on: ubuntu-latest
    name: Publish built container
    needs:
      - lint
      - test
    if: success() && github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for dcspkg server
        uses: macbre/push-to-ghcr@v12
        with:
          image_name: uwcs/dcspkg-server
          github_token: ${{ secrets.GITHUB_TOKEN }}

  cli_release:
    runs-on: ubuntu-latest
    name: Release CLI to crates.io
    needs:
      - lint
      - test
    if: ${{ success() }} && github.ref == 'refs/heads/main' && contains(github.ref, '/tags/v')))
    steps:
      - uses: actions/checkout@v2
      - uses: katyo/publish-crates@v1
        with:
          path: "./dcspkg"
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
