name: Build and publish a Docker image to ghcr.io
on:
  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for dcspkg server
        uses: macbre/push-to-ghcr@v12
        with:
          image_name: dcspkg-server
          github_token: ${{ secrets.GITHUB_TOKEN }}
